// Store facts come from @violeet_perfumess (bio, highlights, posts).
export const STORE = {
  phone: '0959 587 754',
  phoneIntl: '+963 959 587 754',
  whatsapp: 'https://wa.me/963959587754',
  instagram: 'https://www.instagram.com/violeet_perfumess/',
  map: 'https://www.google.com/maps/search/?api=1&query=Byblos+Bank+Shaalan+Damascus',
  mapEmbed: 'https://www.google.com/maps?q=Byblos%20Bank%20Al%20Shaalan%20Damascus&output=embed',
};

// gallery = number of story photos saved from that brand's Instagram highlight.
export const BRANDS = [
  { key: 'dior', name: 'Dior', logo: 'dior.svg', gallery: 23 },
  { key: 'ysl', name: 'Yves Saint Laurent', logo: 'ysl.svg', gallery: 23 },
  { key: 'jpg', name: 'Jean Paul Gaultier', logo: 'jpg.svg', gallery: 59 },
  { key: 'tomford', name: 'Tom Ford', logo: 'tomford.svg', gallery: 5 },
  { key: 'carolina', name: 'Carolina Herrera', logo: 'carolina.svg', gallery: 20 },
  { key: 'lancome', name: 'Lancôme', logo: 'lancome.svg', gallery: 17 },
  { key: 'dg', name: 'Dolce & Gabbana', logo: 'dg.svg', gallery: 26 },
  { key: 'narciso', name: 'Narciso Rodriguez', logo: 'narciso.svg', gallery: 20 },
  { key: 'gucci', name: 'Gucci', logo: 'gucci.svg', gallery: 4 },
  { key: 'azzaro', name: 'Azzaro', logo: 'azzaro.svg', gallery: 4 },
  { key: 'bbw', name: 'Bath & Body Works', logo: 'bbw.svg', gallery: 25 },
  { key: 'ibraq', name: 'IBRAQ by Abdul Samad Al Qurashi', logo: 'ibraq.svg', gallery: 15 },
  { key: 'paco', name: 'Paco Rabanne', logo: 'paco.svg', gallery: 0 },
  { key: 'givenchy', name: 'Givenchy', logo: 'givenchy.svg', gallery: 0 },
  { key: 'armani', name: 'Giorgio Armani', logo: 'armani.svg', gallery: 0 },
  { key: 'valentino', name: 'Valentino', logo: 'valentino.svg', gallery: 0 },
  { key: 'nina', name: 'Nina Ricci', logo: 'nina.svg', gallery: 0 },
  { key: 'boss', name: 'Hugo Boss', logo: 'boss.svg', gallery: 0 },
  { key: 'guerlain', name: 'Guerlain', logo: 'guerlain.svg', gallery: 0 },
  { key: 'issey', name: 'Issey Miyake', logo: 'issey.svg', gallery: 0 },
  { key: 'victoria', name: "Victoria's Secret", logo: 'victoria.svg', gallery: 0 },
];

export const ACCORDS = {
  floral:   { ar: 'زهري', en: 'Floral' },
  sweet:    { ar: 'حلو', en: 'Sweet' },
  vanilla:  { ar: 'فانيلا', en: 'Vanilla' },
  fruity:   { ar: 'فاكهي', en: 'Fruity' },
  citrus:   { ar: 'حمضيات', en: 'Citrus' },
  aromatic: { ar: 'أروماتك', en: 'Aromatic' },
  woody:    { ar: 'خشبي', en: 'Woody' },
  spicy:    { ar: 'توابل', en: 'Spicy' },
  amber:    { ar: 'عنبر', en: 'Amber' },
  musk:     { ar: 'مسك', en: 'Musk' },
  leather:  { ar: 'جلد', en: 'Leather' },
  oud:      { ar: 'عود', en: 'Oud' },
};

// img = [brand gallery folder, photo index]; g = w (women) / m (men) / u (unisex)
export const PRODUCTS = [
  { name: 'Miss Dior', brand: 'dior', img: 0, g: 'w', a: ['floral', 'fruity', 'musk'] },
  { name: 'Sauvage Eau Forte', brand: 'dior', img: 10, g: 'm', a: ['citrus', 'aromatic', 'spicy'] },
  { name: 'Hypnotic Poison', brand: 'dior', img: 13, g: 'w', a: ['vanilla', 'sweet', 'amber'] },
  { name: 'Fahrenheit', brand: 'dior', img: 8, g: 'm', a: ['leather', 'woody', 'spicy'] },
  { name: 'Libre', brand: 'ysl', img: 2, g: 'w', a: ['floral', 'vanilla', 'amber'] },
  { name: 'Y Eau de Parfum', brand: 'ysl', img: 3, g: 'm', a: ['aromatic', 'woody', 'fruity'] },
  { name: 'Black Opium Le Parfum', brand: 'ysl', img: 1, g: 'w', a: ['vanilla', 'sweet', 'floral'] },
  { name: 'Libre Berry Crush', brand: 'ysl', img: 17, g: 'w', a: ['fruity', 'floral', 'vanilla'] },
  { name: 'Le Male Elixir', brand: 'jpg', img: 0, g: 'm', a: ['vanilla', 'amber', 'aromatic'] },
  { name: 'Scandal', brand: 'jpg', img: 3, g: 'w', a: ['sweet', 'floral', 'amber'] },
  { name: 'Le Male Le Parfum', brand: 'jpg', img: 5, g: 'm', a: ['aromatic', 'vanilla', 'woody'] },
  { name: 'Very Good Girl Glam', brand: 'carolina', img: 0, g: 'w', a: ['floral', 'sweet', 'fruity'] },
  { name: '212 VIP Black', brand: 'carolina', img: 10, g: 'm', a: ['aromatic', 'sweet', 'spicy'] },
  { name: 'Bad Boy Extreme', brand: 'carolina', img: 8, g: 'm', a: ['spicy', 'amber', 'sweet'] },
  { name: 'La Vie est Belle', brand: 'lancome', img: 1, g: 'w', a: ['sweet', 'vanilla', 'fruity'] },
  { name: 'Idôle', brand: 'lancome', img: 0, g: 'w', a: ['floral', 'musk', 'citrus'] },
  { name: 'K Eau de Parfum', brand: 'dg', img: 5, g: 'm', a: ['citrus', 'aromatic', 'woody'] },
  { name: 'Light Blue Pour Homme', brand: 'dg', img: 4, g: 'm', a: ['citrus', 'aromatic', 'woody'] },
  { name: 'Devotion Intense', brand: 'dg', img: 10, g: 'w', a: ['sweet', 'vanilla', 'citrus'] },
  { name: 'For Her', brand: 'narciso', img: 0, g: 'w', a: ['musk', 'floral', 'woody'] },
  { name: 'Wanted Eau de Parfum', brand: 'azzaro', img: 1, g: 'm', a: ['aromatic', 'woody', 'spicy'] },
  { name: 'Bloom', brand: 'gucci', img: 0, g: 'w', a: ['floral', 'musk'] },
  { name: 'Lost Cherry', brand: 'tomford', img: 2, g: 'u', a: ['fruity', 'sweet', 'amber'] },
  { name: 'Ombré Leather', brand: 'tomford', img: 4, g: 'u', a: ['leather', 'woody', 'spicy'] },
  { name: 'Jasmin Rouge', brand: 'tomford', img: 0, g: 'w', a: ['floral', 'spicy', 'amber'] },
  { name: 'Guilty Intense Oud', brand: 'gucci', img: 2, g: 'm', a: ['oud', 'amber', 'woody'] },
  { name: 'IBRAQ Collection', brand: 'ibraq', img: 8, g: 'u', a: ['oud', 'musk', 'amber'] },
];

export const imgPath = (brand, i) => `assets/img/${brand}/${String(i).padStart(2, '0')}.webp`;

export const I18N = {
  ar: {
    'nav.home': 'الرئيسية', 'nav.shop': 'العطور', 'nav.brands': 'الماركات', 'nav.visit': 'زورونا',
    'cta.whatsapp': 'اطلب على واتساب', 'cta.brands': 'تصفّح الماركات',
    'hero.title': 'عطرك الأصلي، من الشعلان لكل سوريا',
    'hero.sub': 'المكان الأول لبيع البيرفيوم الأورجينال بدمشق. جرّب العطر على التيستر قبل ما تشتري، ونحنا منوصّلك ياه لباب البيت.',
    'hero.hint': 'انقر على أي عطر ليدور',
    'shop.title': 'على رفوفنا هلّق',
    'shop.sub': 'اختار حسب الرائحة. نفس الإتفاقات الرئيسية اللي منكتبها على كل ستوري.',
    'shop.all': 'الكل', 'shop.w': 'نسائي', 'shop.m': 'رجالي', 'shop.u': 'للجنسين',
    'shop.empty': 'ما في عطر بهالتركيبة على الرف حالياً. شيل أحد الفلاتر أو اسألنا على واتساب.',
    'shop.open': 'شوف الصور',
    'bbw.title': 'Bath & Body Works',
    'bbw.sub': 'بخاخات ولوشن وشموع بروائح الصيف والشتا. متوفر مبيع جملة.',
    'bbw.price': 'سعر القطعة بآخر عرض',
    'bbw.cta': 'اسأل عن الروائح المتوفرة',
    'visit.title': 'زورونا بالشعلان',
    'visit.addr': 'دمشق، الشعلان، جانب بنك بيبلوس',
    'visit.f1': 'كل العطور أورجينال 100%',
    'visit.f2': 'تيستر لكل عطر قبل الشراء',
    'visit.f3': 'توصيل بدمشق وشحن لكل المحافظات',
    'visit.map': 'افتح بخرائط Google', 'visit.call': 'اتصل بنا',
    'foot.line': 'فيوليت للعطور الأصلية، دمشق',
    'brands.title': 'الماركات اللي عنّا',
    'brands.sub': 'كل ماركة إلها صور من رفوفنا. اضغط على الماركة لتشوف العطور المتوفرة متل ما منعرضها بالستوري.',
    'brands.photos': 'صورة من المحل', 'brands.instore': 'متوفرة بالمحل',
    'viewer.close': 'إغلاق', 'viewer.ask': 'اسأل عن هالعطر',
    'lang': 'EN',
  },
  en: {
    'nav.home': 'Home', 'nav.shop': 'Perfumes', 'nav.brands': 'Brands', 'nav.visit': 'Visit',
    'cta.whatsapp': 'Order on WhatsApp', 'cta.brands': 'Browse the brands',
    'hero.title': 'Original perfume, from Al-Shaalan to all of Syria',
    'hero.sub': "Damascus's first stop for original perfume. Try every scent on a tester before you buy, and we'll deliver it to your door.",
    'hero.hint': 'Click any bottle to spin it',
    'shop.title': 'On our shelves now',
    'shop.sub': 'Pick by scent. These are the same main accords we list on every story.',
    'shop.all': 'All', 'shop.w': 'Women', 'shop.m': 'Men', 'shop.u': 'Unisex',
    'shop.empty': "Nothing on the shelf matches that mix right now. Remove a filter or ask us on WhatsApp.",
    'shop.open': 'See photos',
    'bbw.title': 'Bath & Body Works',
    'bbw.sub': 'Mists, lotions and candles in summer and winter scents. Wholesale available.',
    'bbw.price': 'per piece in our latest offer',
    'bbw.cta': 'Ask which scents are in',
    'visit.title': 'Visit us in Al-Shaalan',
    'visit.addr': 'Al-Shaalan, next to Byblos Bank, Damascus',
    'visit.f1': 'Every perfume 100% original',
    'visit.f2': 'A tester for every scent',
    'visit.f3': 'Delivery in Damascus, shipping to every governorate',
    'visit.map': 'Open in Google Maps', 'visit.call': 'Call us',
    'foot.line': 'Violet Original Perfumes, Damascus',
    'brands.title': 'The houses we carry',
    'brands.sub': 'Every brand comes with photos from our shelves. Tap one to see what is in stock, just as we show it in our stories.',
    'brands.photos': 'photos from the store', 'brands.instore': 'In store',
    'viewer.close': 'Close', 'viewer.ask': 'Ask about this perfume',
    'lang': 'عربي',
  },
};
